__title__ = 'TalentTalent'
__description__ = 'Collect distributed / decentralized skills / offers / requests from people. '
__url__ = 'https://github.com/minutogit/TalentTalent/'
__version__ = '0.13.7.beta'
__author__ = 'Sebastian'
__author_email__ = ''
__license__ = ''
__copyright__ = ''