__title__ = 'TalentTalent'
__description__ = 'Collect distributed / decentralized skills / offers / requests from people. '
__url__ = 'https://github.com/minutogit/TalentTalent/'
__version__ = '0.14.6.beta'
__author__ = 'Sebastian Galek'
__author_email__ = 'sgalek@gmx.de'
__license__ = 'MIT License'
__copyright__ = ''